// <auto-generated />
using System;
using FutureSpaceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureSpaceAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230719230616_AddImportDate")]
    partial class AddImportDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("FutureSpaceAPI.Domain.Entities.Launcher", b =>
                {
                    b.Property<Guid>("LaunchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LaunchId");

                    b.ToTable("Launchers");
                });
#pragma warning restore 612, 618
        }
    }
}
